### ISSUE TITLE
hipathia online not uploading

### ISSUE THREAD

**Issue by Jobhanks** [babelomics/hipathia#1]
Hello, 

After my data matrix is validated, I am unable to upload.  The upload bar wheel is scrolling but remains at 0%.  When clicking upload again it says "upload already in progress".  Also get the same issue with experimental design file so it is not a issue of size.

Thank

**Comment by kinzaR** [comment]
Hello,
Thank you for using our tool.
Probably you have this issue because of the encoding of your files, I think that you have an unsupported version of Encoding files ("ISO-8859-2") witch is for For Central-European languages (Polish, Czech, Slovak,...)... 
Please try to covert your file using the UTF-8 or ISO-8859-1  which is the most commonly used encoding...
We are trying to add the "ISO-8859-2" to our supported inputs files, but still not recommended for our web-tools.
If you need any other help, please contact us again.
Thanks
kinza.rian@juntadeandalucia.es

**Comment by Jobhanks** [comment]
Thanks for the help!  That worked.  

One question about the differential expression - 

I did a couple analysis with deseq2 and put the resulting p<0.05 into various GO (reactome, metascape). While some of the up/downregulated genes are found in hiPathia, all the GO categories that I've gotten with reactome or metascape have p<0.00001 but are not significant in hiPathia. The most significant GO hiPathia comes up with are p=0.15 or so.  

I'm wondering if the type of counts (i.e. fpkm, kallisto output) in the data matrix is important.  What program does hiPathia use for differential gene analysis?

Thanks,

**Comment by kinzaR** [comment]
You are welcome!
The input data has to be a **normalized** expression matrix file. [More information about data format](http://hipathia.babelomics.org/doc/doku.php?id=data_format)
We are using a Wilcoxon test with an FDR correction, so the number of samples has to be enough in order to have the results statistically significant.
Please also consider **paired** data in the analysis. When not selected the analysis is performed using **unpaired** parameter for the used statistical [more information...](http://hipathia.babelomics.org/doc/doku.php?id=differential_signaling&s[]=wilcoxon#parameters)
Please give me more information about your input data and your experimental design and also if your data is paired or not, in order t have a clear idea.
Thanks 
kinza.rian@juntadeandalucia.es

**Comment by cankutcubuk** [comment]
Hi all,

I would like to clarify some points about hipathia and its options. It uses normalized gene expression to calculate sub-pathway (circuit) activities and then uses statistical tests (e.g. Wilcoxon) to determine the differentially activated circuits. It does not provide/requiere a list of differentially expressed genes.
The method behind the hipathia is called Mechanistic Pathway Analysis. This method is different and also more advanced than the clasical Gene Set Enrichment tecniques. 

For more details you can check: https://doi.org/10.1093/bib/bby040
https://dx.doi.org/10.18632%2Foncotarget.14107

There is also R package of hipathia:
https://doi.org/doi:10.18129/B9.bioc.hipathia

Happy New Year ;)

**Comment by Jobhanks** [comment]
Thanks for all your responses, I appreciate the help.

I've read over the documentation regarding paired and unpaired and just wanted to clarify: Is it correct to say that when using unpaired, hipathia will determine enrichment based on adjusted p-value?  And if using paired, then hipathia will take into consideration FDR so the enrichment threshold is much more stringent?

I have two RNA-seq experiments where each experiment consists of 2 normal and 2 treated samples. We have some batch effect between the experiments but the results are consistent even when the experiments are analyzed together.  On hipathia, I only get significant signaling pathways when I use the unpaired option.

**Comment by cankutcubuk** [comment]
Hi, 

If you select "Unadjusted" option, it will return the results based on the ordinary p-value. Otherwise, the default option is "adjusted" and the results are given with FDR adjusted p-value. This multiple testing correction is independent from the design of your study (paired or unpaired).

#Paired
The paired option might be selected if all the control and case samples are matching. For example: control samples (A, B, C) and case samples (A, B, C).
Here A, B, C are showing the patients. Control A and Case A come from the same patient (patient A) ... Samples of different conditions are fully paired. 

#Unpaired (default option)
You have to select unpaired option if you have a study design like:

Control samples (A, B, C) VS. Case samples (A, B, C, D, E) 
or
Control samples (A, B, C) VS. Case samples (K, L, M)
As you can see, in these examples, the samples of different conditions are NOT paired.


The case and control samples can be thought as tumor tissue and blood.
 
Best wishes
